export const CATEGORIES_LOADING = "CATEGORIES_LOADING";

export const CATEGORIES_SUCCESS = "CATEGORIES_SUCCESS";

export const CATEGORIES_ERROR = "CATEGORIES_ERROR";

export const CLEAR_CATEGORIES = 'CLEAR_CATEGORIES'; 

export const CATEGORIES_SEARCH_LOADING = "CATEGORIES_SEARCH_LOADING";

export const CATEGORIES_SEARCH_SUCCESS = "CATEGORIES_SEARCH_SUCCESS";

export const CATEGORIES_SEARCH_ERROR = "CATEGORIES_SEARCH_ERROR";

export const CLEAR_SEARCH_CATEGORIES = 'CLEAR_SEARCH_CATEGORIES'; 


