export const CATEGORIES_LOADING = "CATEGORIES_LOADING";

export const CATEGORIES_SUCCESS = "CATEGORIES_SUCCESS";

export const CATEGORIES_ERROR = "CATEGORIES_ERROR";

export const CLEAR_CATEGORIES = 'CLEAR_CATEGORIES'; 


