export const POSTS_LOADING = "POSTS_LOADING";

export const POSTS_SUCCESS = "POSTS_SUCCESS";

export const POSTS_ERROR = "POSTS_ERROR";

export const CLEAR_POSTS = 'CLEAR_POSTS'; 

export const POSTS_SEARCH_LOADING = "POSTS_SEARCH_LOADING";

export const POSTS_SEARCH_SUCCESS = "POSTS_SEARCH_SUCCESS";

export const POSTS_SEARCH_ERROR = "POSTS_SEARCH_ERROR";

export const CLEAR_SEARCH_POSTS = 'CLEAR_SEARCH_POSTS';  


